# Generated by Django 4.2 on 2025-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
