# Generated by Django 4.2 on 2025-05-23 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classrooms", "0002_alter_classroom_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="teacher_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classrooms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
