# Generated by Django 4.2 on 2025-05-23 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_alter_classroom_teacher_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classroom",
            old_name="teacher_name",
            new_name="teacher",
        ),
    ]
