# Generated by Django 4.2 on 2025-11-08 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0004_rename_teacher_name_classroom_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="date_of_birth",
        ),
    ]
