# Generated by Django 4.2 on 2026-02-17 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0007_alter_student_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="classroom",
        ),
        migrations.AddField(
            model_name="student",
            name="classrooms",
            field=models.ManyToManyField(
                related_name="students", to="classrooms.classroom"
            ),
        ),
    ]
