# Generated by Django 4.2 on 2026-05-09 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classrooms", "0009_enrollmentrequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="enrollmentrequest",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="enrollmentrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("student_request", "Student Request"),
                    ("teacher_invitation", "Teacher Invitation"),
                ],
                default="student_request",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollmentrequest",
            unique_together={("student", "classroom", "request_type")},
        ),
    ]
