# Generated by Django 4.2 on 2025-11-22 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("question_bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answeroption",
            options={
                "ordering": ["question", "order"],
                "verbose_name": "Answer Option",
                "verbose_name_plural": "Answer Options",
            },
        ),
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["subject", "order", "name"],
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
            },
        ),
        migrations.AlterModelOptions(
            name="section",
            options={
                "ordering": ["chapter", "order", "name"],
                "verbose_name": "Section",
                "verbose_name_plural": "Sections",
            },
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={
                "ordering": ["name"],
                "verbose_name": "Subject",
                "verbose_name_plural": "Subjects",
            },
        ),
        migrations.AddField(
            model_name="answeroption",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Thứ tự hiển thị (A=0, B=1, C=2...)"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="chapter",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Thứ tự chương (1, 2, 3...)"
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="question",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Soft delete flag"),
        ),
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.FloatField(
                default=1.0, help_text="Điểm tối đa cho câu hỏi này"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="section",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="section",
            name="order",
            field=models.IntegerField(default=0, help_text="Thứ tự mục (1, 2, 3...)"),
        ),
        migrations.AddField(
            model_name="section",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="subject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="is_correct_bool",
            field=models.BooleanField(
                blank=True, help_text="TFE: True/False - đáp án đúng", null=True
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="score_percentage",
            field=models.FloatField(
                default=0.0,
                help_text="MC: 100.0 = đúng hoàn toàn, 50.0 = đúng một phần, 0.0 = sai",
            ),
        ),
        migrations.AlterField(
            model_name="answeroption",
            name="text",
            field=models.TextField(help_text="Nội dung lựa chọn"),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subjects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chapter",
            unique_together={("subject", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("chapter", "order")},
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["section", "is_active"], name="question_ba_section_66bce0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="question_ba_questio_bfbc84_idx"
            ),
        ),
    ]
