# Generated by Django 4.2 on 2026-01-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "question_bank",
            "0002_alter_answeroption_options_alter_chapter_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="points",
        ),
    ]
