# Generated by Django 4.2 on 2026-01-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0003_remove_question_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answeroption",
            name="score_percentage",
        ),
    ]
