# Generated by Django 4.2 on 2026-05-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0004_remove_answeroption_score_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.URLField(
                blank=True, help_text="URL ảnh đính kèm câu hỏi (Cloudinary)", null=True
            ),
        ),
    ]
