# Generated by Django 4.2 on 2025-11-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="authprovider",
            options={},
        ),
    ]
