# Generated by Django 4.2 on 2025-11-10 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_authprovider_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthProvider",
        ),
    ]
