# Generated by Django 4.2 on 2025-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
