# Generated by Django 4.2 on 2025-12-21 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("online_exams", "0002_exam_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="exam",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
