# Generated by assistant on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_exams", "0003_exam_created_at_exam_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="publish_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
