# Generated by Django 4.2 on 2025-05-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0001_initial"),
        ("exam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="classrooms.classroom",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="classrooms.classroom",
            ),
        ),
        migrations.DeleteModel(
            name="Classroom",
        ),
    ]
