# Generated by Django 4.2 on 2025-05-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0004_rename_teacher_name_classroom_teacher"),
        ("exam", "0002_submission_student_alter_test_classroom_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="classrooms.student",
            ),
        ),
    ]
