# Generated by Django 4.2 on 2025-11-02 12:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0003_alter_submission_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="submission_image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="submission_images"
            ),
        ),
    ]
