# Generated by Django 4.2 on 2025-11-15 03:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("classrooms", "0007_alter_student_user"),
        ("exam", "0004_alter_submission_submission_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnswerDetected",
            new_name="PaperAnswerDetected",
        ),
        migrations.RenameModel(
            old_name="Submission",
            new_name="PaperSubmission",
        ),
        migrations.RenameModel(
            old_name="Test",
            new_name="PaperTest",
        ),
        migrations.RenameModel(
            old_name="Question",
            new_name="PaperTestQuestion",
        ),
        migrations.RenameModel(
            old_name="UserAnswer",
            new_name="PaperUserAnswer",
        ),
    ]
