# Generated by Django 4.2 on 2026-02-19 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0004_remove_answeroption_score_percentage"),
        ("exam", "0005_rename_answerdetected_paperanswerdetected_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papertestquestion",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="papertest",
            name="questions",
            field=models.ManyToManyField(
                related_name="paper_tests",
                through="exam.PaperTestQuestion",
                to="question_bank.question",
            ),
        ),
        migrations.AddField(
            model_name="papertestquestion",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="papertestquestion",
            name="question",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question_bank.question",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="papertestquestion",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paper_questions",
                to="exam.papertest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="papertestquestion",
            unique_together={("test", "question")},
        ),
        migrations.RemoveField(
            model_name="papertestquestion",
            name="correct_answer",
        ),
        migrations.RemoveField(
            model_name="papertestquestion",
            name="score",
        ),
        migrations.RemoveField(
            model_name="papertestquestion",
            name="text",
        ),
    ]
