# Generated by Django 4.2 on 2026-03-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0006_alter_papertestquestion_options_papertest_questions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paperanswerdetected",
            name="confidence",
        ),
        migrations.RemoveField(
            model_name="paperuseranswer",
            name="selected_option",
        ),
        migrations.AddField(
            model_name="papertest",
            name="num_variants",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="paperuseranswer",
            name="selected_options",
            field=models.JSONField(
                default=list, help_text="List of selected option indices"
            ),
        ),
        migrations.CreateModel(
            name="PaperTestVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant_code",
                    models.CharField(
                        help_text="Mã đề: A, B, C, 101, 102...", max_length=10
                    ),
                ),
                (
                    "question_order",
                    models.JSONField(
                        help_text="List ID câu hỏi theo thứ tự: [5,2,8,1,3...]"
                    ),
                ),
                (
                    "answer_shuffles",
                    models.JSONField(
                        help_text="Thứ tự đáp án mỗi câu: {1: [2,0,3,1], 2: [1,3,0,2]...}"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="exam.papertest",
                    ),
                ),
            ],
            options={
                "ordering": ["variant_code"],
                "unique_together": {("test", "variant_code")},
            },
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="exam.papertestvariant",
            ),
        ),
    ]
