# Generated by Django 4.2 on 2026-03-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0007_remove_paperanswerdetected_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papersubmission",
            name="detected_mssv",
            field=models.CharField(
                blank=True,
                help_text="MSSV detected from OMR bubbles",
                max_length=20,
                null=True,
            ),
        ),
    ]
