@startuml
title SD Create Online Test

actor ": Teacher" as User

boundary ": OnlineExamManagementView" as View
control ": OnlineExamController" as Controller
entity ": Exam" as Exam
entity ": ExamQuestion" as ExamQuestion

' ===== 1. Khởi tạo Đề thi Online =====
User -> View : 1: createExam(data : Object) : void
View -> Controller : 1.1: createExam(data : Object) : Exam

Controller -> Exam : 1.1.1: <<create>>\ncreate(data : Object) : Exam
activate Exam
Controller <-- Exam
deactivate Exam

' ===== 2. Gắn danh sách câu hỏi vào đề =====
Controller -> ExamQuestion : 1.1.2: <<create>>\nbulkCreate(examQuestions : List) : List
activate ExamQuestion
Controller <-- ExamQuestion
deactivate ExamQuestion

View <-- Controller
User <-- View : 1.2: displaySuccess() : void

@enduml
